### ISSUE TITLE
Please add a Blacklist

### ISSUE THREAD

**Issue by Dud3z** [RetroDriven/MiSTerWallpapers#1]
Most of the Wallpapers are awesome... but some (Splatterhouse) are very disturbing... can you add some kind of blacklist to not sync some of the wallpapers? I Know there is a selfmanage function but because of one single wallpaper i dont want to self manage everything. THX! thatz script is awesome!

**Comment by RetroDriven** [comment]
You're welcome and thanks for the feedback. 

I'll take a look at this and see if I can add a Keyword Blacklist to Filter out what you don't want to Download.

**Comment by RetroDriven** [comment]
This should be all set now with v1.1 via BLACKLIST Ini option. Please test this out and let me know if it's working on your end.
