### ISSUE TITLE
Remove Sexual/Adult Themed Wallpaper

### ISSUE THREAD

**Issue by davidonabus** [RetroDriven/MiSTerWallpapers#5]
Retro gaming is for children too. Can we get rid of the Sexual/Adult Themed content (ex. Bowsette Fan Club).

Thanks

**Comment by RetroDriven** [comment]
You can use the INI file to Blacklist/Filter these out.

**Comment by davidonabus** [comment]
Thanks

**Comment by RetroDriven** [comment]
You're welcome
